#!/usr/bin/env python

# (c) 2015, Chen Jiaxing <justina.j.chen@gmail.com>
#
# This file is part of Thoth
#
# Thoth CLI Tool is distributed in the hope that it will be useful
# for App compiling, packaging and deploying.

########################################################

import optparse
import sys

class Cli(object):
    ''' code behind bin/thoth '''

    def __init__(self):
        pass

    def parse(self):
        ''' create and options parser for bin/thoth '''

        parser = optparse.OptionParser(description='Thoth Command Line Tool',
                                        prog='thoth',
                                        version='thoth 0.1',
                                        usage='%prog -c -p -d')
        parser.add_option('--compile', '-c', default="java", help='complie the source codes')
        parser.add_option('--package', '-p', default="tomcat", help='package the compiled files')
        parser.add_option('--run', '-r', default="jetty", help='run project')

        options, args = parser.parse_args()
        if len(args) == 0 or len(args) > 1:
            parser.print_help()
            sys.exit(1)

        return (options, args)

    def run(self, options, args):
        ''' use Runner lib to to SSH things '''

        result = 'Start Thoth...'

        if options.compile:
            result = 'Start compiling %s' % args[0]
        elif options.package:
            result = 'Start packaging %s' % args[0]
        elif options.run:
            result = 'Start deploying to %s' % args[0]

        return result


#######################################################

if __name__ == '__main__':
    try:
        cli = Cli()
        (options, args) = cli.parse()
        result = cli.run(options, args)

    except Exception, e:
        print("ERROR: %s" % str(e))
        sys.exit(1)

    sys.exit(result)
